### ISSUE TITLE
Update Inaccessible API URL in README

### ISSUE THREAD

**Issue by kev065** [learn-co-curriculum/python-p4-working-with-apis#11]
### Canvas Link

https://my.learn.co/courses/654/assignments/33307?module_item_id=83831

### Concern

The URL for the API endpoint provided in the README file on line 90 (http://data.cityofnewyork.us/resource/uvks-tn5n.json) is currently inaccessible. 

### Suggested Changes

I suggest updating the URL to an archived version of the same resource available on the Wayback Machine. The URL is: https://web.archive.org/web/20180303155827/https://data.cityofnewyork.us/resource/uvks-tn5n.json

**Comment by AlveeM** [comment]
An updated lesson is being pushed out:
https://github.com/learn-co-curriculum/python-p4-working-with-apis-v2
