### ISSUE TITLE
API Changed and Dataset Appears to Not be Available

### ISSUE THREAD

**Issue by ckelly38** [learn-co-curriculum/python-p4-working-with-apis#12]
### Canvas Link

https://learning.flatironschool.com/courses/6560/assignments/243036?module_item_id=571687

### Concern

When I opened the link like it says, I got an error.

// 20240102164658
// https://data.cityofnewyork.us/resource/uvks-tn5n.json

{
  "error": true,
  "message": "You must be logged in to access this resource"
}

It appears the dataset is no longer available. A TC made an account and still had trouble accessing it or could not figure it out quickly. Copying and pasting solution code, then submitting that to CodeGrade let the placeholder test pass. So we need a different API. Probably something like Weather API for instance that is not going to go away.

### Suggested Changes

Use a different API something like Weather API for instance.

**Comment by AlveeM** [comment]
Thank you for flagging this.

We have pushed out a new lesson with a different API:
https://github.com/learn-co-curriculum/python-p4-working-with-apis-v2
