### ISSUE TITLE
Working with API's (Phase 4) - NYC API requires authentication

### ISSUE THREAD

**Issue by tyjsmith1** [learn-co-curriculum/python-p4-working-with-apis#13]
### Canvas Link

https://learning.flatironschool.com/courses/7026/assignments/264217?module_item_id=632841

### Concern

API requires authentication. Im unable to access the data to complete the lab.

[after-school club data set](https://dev.socrata.com/foundry/data.cityofnewyork.us/szgz-awuh)

![image](https://github.com/learn-co-curriculum/python-p4-working-with-apis/assets/95344047/5eb81fb2-12e8-453f-9536-07cc50c07c1e)

### Suggested Changes

Use a different public API

**Comment by AlveeM** [comment]
Thanks for bringing this to our attention.

We have created an updated lesson which you can view here:
https://github.com/learn-co-curriculum/python-p4-working-with-apis-v2
