### ISSUE TITLE
API is no longer open

### ISSUE THREAD

**Issue by chayavogel** [learn-co-curriculum/python-p4-working-with-apis#14]
### Canvas Link

https://learning.flatironschool.com/courses/6876/assignments/246514?module_item_id=581102

### Concern

The api provided now requires authentication so you can't do the lab

**Comment by AlveeM** [comment]
Thank you for notifying us of the change.

We have created a new lesson:
https://github.com/learn-co-curriculum/python-p4-working-with-apis-v2
